### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#10]
https://github.com/ZakharovAleksey/yandex_cpp/blob/159822a77f9d0672a6b07fb9c48d92e441b42c17/sprint_1/server.h#L7

Предлагаю улучшить именование переменных. В коде есть сокращения например freq, inv. Это не полноценные слова и они могут значить все что угодно и это нехорошо.

Codestyle: Имена переменных должны быть длинными и понятными. Каждый раз, когда вы пишете одно-двух-буквенное название переменной или используете что-то вроде cur, должно возникать неприятное чувство

Если сокращение используется в теории или книгах, то по причине сокращения кода. В реальных программах рекомендуется писать подробные и значащие имена.

Предлагаю в нашем коде тоже это сделать т.е.просмотреть весь код, убрать все сокращения и абстракции. Сделать имена понятными, чтобы код стал самодокументируемым.

Практически никогда лучше не писать сокращенно и/или малоинформативно idx, cur, curr, it, iter, cmp, comp, diff, tmp, temp, ptr, res, len, sz, beg, mid, gen, pred и т.д.

**Comment by d13mon** [comment]
kEps - это что ? даже epsilon нас не устроит т.к это просто буква греческого алфавита

**Comment by d13mon** [comment]
server_ns  имя не ясно. ns это просто буквы для читателя кода. server_namespace писать не нужно, лучше придумать короткое и лаконичное имя без сокращений

**Comment by d13mon** [comment]
ComputeWordInverseDocumentFreq

**Comment by d13mon** [comment]
inv_word_count

**Comment by ZakharovAleksey** [comment]
Поправил все моменты + пробежался по коду и вроде не нашел похожих моментов.

1. `kEps` -> `kEqualityThreshold`
2. `ComputeWordInverseDocumentFreq` -> `ComputeWordInverseDocumentFrequency`
3. `inv_word_count` -> `inverse_word_count`
4. Namesapce оставил `server` - так как, если я понимаю правильно, то в этом курсе мы будем делать поисковый сервер. И тогда, в дальнейшем, мне кажется логичным внути глобального `web` namesapce: вынести часть функций, например в namespace `utility`, взаимодействие с сервером оставить в namespace `server` а клиентскую часть вынести в namespace `client`. Ну и внутри каждого из выышеперечисленных будут свои.

**Comment by d13mon** [comment]
Отлично! :+1:
