### ISSUE TITLE
⚠️req

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#100]
https://github.com/ZakharovAleksey/yandex_cpp/blob/6c87c59ce5ab99b95a21766a5f98a7d75e024b65/src/sprint_10/request_handler.h#L7

Из постановки:
> Организуйте структуру программы в виде следующих модулей:
> geo — объявляет координаты на земной поверхности и вычисляет расстояние между ними;
> domain — классы основных сущностей предметной области, описывают автобусы и остановки;
> transport_catalogue — модуль транспортного каталога;
> **request_handler — модуль для обработки запросов. Играет роль Фасада, который упрощает взаимодействие с транспортным каталогом;**
> json — ваша улучшенная библиотека для парсинга и вывода JSON;
> json_reader — выполняет разбор JSON данных, построенных в ходе парсинга и формирует массив JSON-ответов;
> main — основной модуль программы.
> 

Реализуем в данном модуле класс:

```
class RequestHandler {
public:
    RequestHandler(const TransportCatalogue& db, const renderer::MapRenderer& renderer);

    std::optional<BusStat> GetBusStat(const std::string_view& bus_name) const;

    const std::unordered_set<BusPtr>* GetBusesByStop(
        const std::string_view& stop_name) const;

    svg::Document RenderMap() const;

private:
    const TransportCatalogue& db_;
    const renderer::MapRenderer& renderer_;
};

```

Заведем 2 файла - request_handler .h и cpp

В них реализуем класс, интерфейс которого представлен выше

Он будет фасадом (можно почитать про данный паттерн проектирования)  т.е предоставлять простой интерфейс для других, более сложных модулей. 
Простыми словами будет дергать методы MapRenderer и TransportCatalogue

**Comment by ZakharovAleksey** [comment]
@d13mon - добрый день! :)

Постараюсь это переделать, пока никак не найду времени. Выложил на ревью задачу следующего спринта, попробую по ходу править ваше замечание...

**Comment by d13mon** [comment]
Добрый!

Исправим тогда в 12-м спринте

**Comment by ZakharovAleksey** [comment]
Сделал класс фасад, по предложенному подходу.
