### ISSUE TITLE
⚠️builder

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#101]
https://github.com/ZakharovAleksey/yandex_cpp/blob/7d0435eb30650aed97cf0786e12c7434b8b41edf/src/sprint_11/json_builder.h#L30-L87

Сделаем контекст вложенным классом для Builder
 ```
class BaseContext {
    public:      
        Node Build();
        DictValueContext Key(std::string key);
        BaseContext Value(Node::Value value);
        DictItemContext StartDict() ;
        ArrayItemContext StartArray();
        BaseContext EndDict(); 
        BaseContext EndArray();
    private:
        Builder& builder_;
    };
    
    class DictValueContext : public BaseContext {...   
    };
    
    class DictItemContext : public BaseContext {   ... 
    };
    
    class ArrayItemContext : public BaseContext { ...  
    };
```

**Comment by d13mon** [comment]
в силе в 12-м

**Comment by ZakharovAleksey** [comment]
Немного не понял почему это необходимо - это захламит сам класс, сделав код трудно читаемым.

И почему `BaseContext ` класс в таком виде: почему имеет все методы, ыроде идея была как-раз разбить на контексты, которые имеют методы которые имеют смысл для этого `node`.

**Comment by d13mon** [comment]
- Все методы он имеет потому что вызывает методы билдера, а билдер  должен иметь все т.к предоставляет паблик интерфейс:

DictValueContext Key(std::string key);
    BaseContext Value(Node::Value value);
    DictItemContext StartDict();
    ArrayItemContext StartArray();
    BaseContext EndDict();
    BaseContext EndArray();
    
    в производных контекстах мы удаляем ненужное через  = delete
    
    - Внтури класс размещается когда он не имеет особого смысла сам по себе. Контекст - это часть класса билдера. лучше не засорять им пространство имен

**Comment by ZakharovAleksey** [comment]
Хорошо, поправлю как только будет свободная минутка :)
