### ISSUE TITLE
⚠️именование: параметр с типом Builder называется response

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#102]
https://github.com/ZakharovAleksey/yandex_cpp/blob/7d0435eb30650aed97cf0786e12c7434b8b41edf/src/sprint_11/json_reader.cpp#L45-L58

**Comment by d13mon** [comment]
в силе

**Comment by ZakharovAleksey** [comment]
Переименовал на `json_builder`
