### ISSUE TITLE
size-t

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#104]
https://github.com/ZakharovAleksey/yandex_cpp/blob/132d4aac8c828389a4a92d9d24308991206bc3e2/src/sprint_12/transport_router.h#L84

- Codestyle: Рекомендации по использованию целых типов
https://google.github.io/styleguide/cppguide.html#Integer_Types

- Unsigned целые (кроме size_t в качестве индексов и размеров) в целом не рекомендуются к использованию из-за потенциальных проблем с ними.
Общая рекомендация по коду.

 - size_t может использоваться в коде только в качестве индексов и размеров исходя из семантики типа.
https://en.cppreference.com/w/cpp/types/size_t

**Comment by ZakharovAleksey** [comment]
Поменял везеде на `int` :)
