### ISSUE TITLE
cnaming

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#105]
https://github.com/ZakharovAleksey/yandex_cpp/blob/132d4aac8c828389a4a92d9d24308991206bc3e2/src/sprint_12/transport_router.h#L84

Лучше именовать константы согласно кодстайлу.
https://google.github.io/styleguide/cppguide.html#Constant_Names

В капслоке сложнее написать, поэтому при разработке на написание таких констант тратится лишнее время.

- Это касается как глобальных, так и статических локальных констант и констант класса.

**Comment by d13mon** [comment]
также неясно почему even

**Comment by ZakharovAleksey** [comment]
Поменял везеде на `kPrimeValue`
