### ISSUE TITLE
граф можем хранить не по указателю

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#106]
https://github.com/ZakharovAleksey/yandex_cpp/blob/132d4aac8c828389a4a92d9d24308991206bc3e2/src/sprint_12/transport_router.h#L98

**Comment by ZakharovAleksey** [comment]
Храню по указателю, тк: 
1. На начальный момент неизвеcтно количество вершин, требуемое как аргумент конструктора
2. При использовании конструктора по умолчанию, потом нет метода, который переалоцировал бы память под хранение вершин графа, поэтому использую конструктор с числом вершин

```cpp
routes_ = std::make_unique<Graph>(stop_to_vertex_.size() * 2);
```

**Comment by d13mon** [comment]
ок, не критично
