### ISSUE TITLE
deinit

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#108]
https://github.com/ZakharovAleksey/yandex_cpp/blob/fed4b1a37d219bb1e90b95fa10784156ac84800f/src/sprint_13/vector.h#L228

Выделим метод деинициализации, в который уберет повторяющийся код с условием:

```if constexpr (std::is_nothrow_move_constructible_v<T> || !std::is_copy_constructible_v<T>) ```

**Comment by ZakharovAleksey** [comment]
Сделал метод `DeInitializeMemory` и использовал его везде где встречается это выражение

Изменения в ветке [master](https://github.com/ZakharovAleksey/yandex_cpp)
