### ISSUE TITLE
~

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#109]
https://github.com/ZakharovAleksey/yandex_cpp/blob/fed4b1a37d219bb1e90b95fa10784156ac84800f/src/sprint_13/vector.h#L186

Не вызываем деструкторы напрямую

есть ф-ии группы std::destroy_***

**Comment by ZakharovAleksey** [comment]
Переделал. Сделал так, тк показалось красивей :)

Изменения в ветке [master](https://github.com/ZakharovAleksey/yandex_cpp).
