### ISSUE TITLE
new может бросить исключение

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#110]
https://github.com/ZakharovAleksey/yandex_cpp/blob/fed4b1a37d219bb1e90b95fa10784156ac84800f/src/sprint_13/vector.h#L173

должен быть в блоке try {}

**Comment by ZakharovAleksey** [comment]
Передвинул в `try{}-catch{}` блок) 

Изменения в ветке [master](https://github.com/ZakharovAleksey/yandex_cpp)

**Comment by d13mon** [comment]
не увидел в ветке по ссылке

new на месте

**Comment by ZakharovAleksey** [comment]
Да, извинаюсь - пропустил. 
Добавил изменения в ветке `master`.
