### ISSUE TITLE
IsTrue: нет проверок 

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#113]
https://github.com/ZakharovAleksey/yandex_cpp/blob/aa65912aa34fb0a9460a34376ab223f48cae27b4/src/sprint_15/runtime.cpp#L42-L50

- Проверим указатели на nullptr

- проверим что object не пустой, иначе вернем false

- Проверим p->GetValue(): для чисел сравним с 0, для строк проверим на непустоту

**Comment by ZakharovAleksey** [comment]
Done: добавил пропущенную проверку на то что `object` не пустой
