### ISSUE TITLE
lexer private

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#114]
https://github.com/ZakharovAleksey/yandex_cpp/blob/aa65912aa34fb0a9460a34376ab223f48cae27b4/src/sprint_15/lexer.h#L187-L190

- Реализуем 
Token Lexer::NextTokenImpl(), который будем вызывать в CTR и NextToken() для иниц-ии current_token_

- храним  как член класса: Token current_token_; Не храним список токенов

**Comment by ZakharovAleksey** [comment]
Done!

Теперь вместо вектора `Token` один единственный `current`, а для более корректной обработки `indent` был добавлен класс `IndentParser` который оперделяет `indent` и отрезает его от строки.
