### ISSUE TITLE
std

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#12]
https://github.com/ZakharovAleksey/yandex_cpp/blob/159822a77f9d0672a6b07fb9c48d92e441b42c17/sprint_1/server.cpp#L13

Codestyle: 

Лучше не включать все объявления из пространства имен через директиву using namespace <name>;
Если использовать данную директиву, то локально в функциях-методах

https://google.github.io/styleguide/cppguide.html#Namespaces

Иначе мы загрязняем пространство имен. 

Возможен вариант:

```
using std::string;
using std::vector;
```

в CPP файлах, но не хидерах (.H)

или где-то можно:

```
void foo() { 
    using namespace std;
    ...
    cout << 1 << endl;
}
```
Общее правило по using: используем из пространства имен (в том числе из std) только то, что нужно. Using используем максимально локализованно. 

Лучший же вариант (который обычно в реальных проектах и в образцовом коде) - это писать через пространство имен т.е std::string, std::vector, std::remove - этим мы однозначно определяем имя

Пример из STL:
```
#include <algorithm>
#include <iostream>
#include <vector>
#include <iterator>
#include <numeric>
 
int main()
{
    std::vector<int> from_vector(10);
    std::iota(from_vector.begin(), from_vector.end(), 0);
 
    std::vector<int> to_vector;
    std::copy(from_vector.begin(), from_vector.end(),    std::back_inserter(to_vector));
 
    std::cout << "to_vector contains: ";
 
    std::copy(to_vector.begin(), to_vector.end(),    std::ostream_iterator<int>(std::cout, " "));
    std::cout << '\n';
 
    std::cout << "odd numbers in to_vector are: ";
 
    std::copy_if(to_vector.begin(), to_vector.end(),  std::ostream_iterator<int>(std::cout, " "),
                 [](int x) { return (x % 2) == 1; });
    std::cout << '\n';
}
```

**Comment by ZakharovAleksey** [comment]
Сделал максимально понятно и просто, с моей точки зрения :)

Добавил в *.cpp файл `using std::vector;` и `using std::string`. 
В остальных местах используется `std::`.
