### ISSUE TITLE
почему у нас методы, изменяющие член данных, константные?

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#120]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8028c505d59aee847c28fe1cdbbad7704a258f55/src/sprint_16/cell.cpp#L252-L257

использование mutable, квалификатор const для номинально неконстантных методов -  это все "костыли"

сделаем без них

**Comment by ZakharovAleksey** [comment]
Согласен - удалил эти методы. Теперь изменение `ascending_cells_` проиходит напрямую в методах где это необходимо.
