### ISSUE TITLE
cell

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#121]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8028c505d59aee847c28fe1cdbbad7704a258f55/src/sprint_16/cell.h#L75

- Сделаем иерархию реализаций

У нас будет интерфейс реализации
class Cell::Impl {
public:
    virtual ~Impl() = default;

    virtual Value GetValue() const = 0;
    virtual std::string GetText() const = 0;
};

и классы

class Cell::EmptyImpl : public Impl 
class Cell::TextImpl : public Impl 

и так далее

- Уберем все эти классы реализации из H, разместим их код в CPP

Поместим объявление реализации в приватную секцию класса Cell
```
private:
    class Impl;
    class EmptyImpl;
    class TextImpl;
    class FormulaImpl;
```

- кеш храним в реализации FormulaImpl как
mutable std::optional<FormulaInterface::Value> cached_value_;

**Comment by ZakharovAleksey** [comment]
По сути у меня был тот-же подход, только:
* `Impl` у меня `CellValueInterface`
* `EmptyImpl` у меня `EmptyCellValue`
* `TextImpl` у меня `TextCellValue`
* `FormulaImpl` у меня `FormulaCellValue`

Переместил объявление этих классов в `private` секцию. Имплементацию перенес в `cell.cpp`.
```cpp
private:  // Types and using
    class CellValueInterface;
    class EmptyCellValue;
    class TextCellValue;
    class FormulaCellValue;

    using CellValueIntefaceUPtr = std::unique_ptr<CellValueInterface>;
```
