### ISSUE TITLE
set

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#122]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8028c505d59aee847c28fe1cdbbad7704a258f55/src/sprint_16/cell.cpp#L117

-  Заведем и будем заполнять временную переменную с реализацией: std::unique_ptr<Impl> new_impl;

После успешной проверки на циклические ссылки переместим ее в impl_

при неуспешной бросаем исключение

- Заведем для '=' и '\'' именованные константы

-  Проверку на Escape sign ('\'')  разместим в Value Cell::TextImpl::GetValue() 

- Метод проверки циклических ссылок должен вызываться напрямую

это должен быть константный метод проверки, не меняет класс

- Лучше выделить отдельный метод апдейта

**Comment by ZakharovAleksey** [comment]
У меня тот-же подход.

Внутри метода `Cell:Set()`:
* Создание временной переменной `CellValueInterface`.
```cpp
auto tmp = TryCreateCell(text, sheet_);
```
* Проверка на цикличность и выброс исключение, если цикл найден (метод константный)
```cpp
if (CellsStorage visited{this}; HasCircularDependency(this, tmp, visited))
        throw CircularDependencyException("");
```
* Перемещение временной переменной `CellValueInterface` в постоянное значение:
```cpp
value_ = std::move(tmp);
```
* Обновление связей. Не выносил в отдельный метод, тк это небольшая последовательность шагов, которая нигде не дублируется. Помещается на 10 строчек. Не ухудшает code-readability.

```cpp
if (!descending_cells_.empty())
        RemoveOldConnections();

if (auto* formula_cell = TryInterpretAsFormula(value_))
    EstablishNewConnections(formula_cell);

if (!ascending_cells_.empty()) {
    CellsStorage visited{this};
    InvalidateReferencedCellsCache(visited);
}
```


P.S. Проверку на Escape sign (''') разместим в Value Cell::TextImpl::GetValue(). Мой метод

```cpp
[[nodiscard]] Value GetValue() const override {
        return (!text_.empty() && text_.front() == kEscapeSign) ? text_.substr(1) : text_;
}
```
