### ISSUE TITLE
 - std::vector<std::vector<>> cells_; - не самый эффективный вариант контейнера для хранения  

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#123]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8028c505d59aee847c28fe1cdbbad7704a258f55/src/sprint_16/sheet.h#L11

**Comment by ZakharovAleksey** [comment]
Согласен что это не самый эффективный вариант хранения :)

Можно было бы хранить в `unordered_map` и обеспечить методам `SetCell`, `GetCell`, `ClearCell` порядок `O(1)` проверяя наличие клетки через метод `count()`. 

```cpp
using Storage = std::unordered_map<Position, CellInterface>; 
```

Но решил оставить такую реализацию поскольку в подсказке и советах к задаче дана именно такая структура данных. 
И если это возможно, хотелось бы оставить в таком виде :)
