### ISSUE TITLE
length

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#17]
https://github.com/ZakharovAleksey/yandex_cpp/blob/159822a77f9d0672a6b07fb9c48d92e441b42c17/main.cpp#L41

Codestyle: Длина строки не должна превышать 80 символов
https://google.github.io/styleguide/cppguide.html#Line_Length

предлагаю выделить переменную для лямбда

**Comment by ZakharovAleksey** [comment]
Для конкретного места в коде создал лямбду.

Проверил длину по всему коду.
