### ISSUE TITLE
После запятой всегда пробел нужен

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#18]
https://github.com/ZakharovAleksey/yandex_cpp/blob/61de83fc28d7ce53658d033ae3e300e114733a3e/sprint_1/server.cpp#L147

**Comment by ZakharovAleksey** [comment]
Извиняюсь, не заметил проблему по той же причине что и в [этом](https://github.com/ZakharovAleksey/yandex_cpp/issues/20#issue-817914847) коментарии.
