### ISSUE TITLE
WordsDocIdTuple

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#19]
https://github.com/ZakharovAleksey/yandex_cpp/blob/61de83fc28d7ce53658d033ae3e300e114733a3e/sprint_1/server.h#L42

Введение данного псевдонима - неплохое решение

Но именование типа  усложненное.

Doc - сокращение
Tuple - излишняя информация. Мы не пишем название структуры в имени вроде std::vector<int>  vector_of_ids, пишем просто ids

Лучше что-то вроде DocumentsInfo, MatchedData

**Comment by ZakharovAleksey** [comment]
Поправил - на мой взгляд `WordsInDocumentInfo` достаточно описывает данный тип.
