### ISSUE TITLE
форматирование: пробелы

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#20]
https://github.com/ZakharovAleksey/yandex_cpp/blob/61de83fc28d7ce53658d033ae3e300e114733a3e/sprint_1/server.cpp#L68

**Comment by ZakharovAleksey** [comment]
Поправил.

Не заметил, так как решил попробовать использовать Clion. И там эта строчка выглядит следующим образом:

![image](https://user-images.githubusercontent.com/18697972/109388851-ae945780-791a-11eb-885e-736967b8d762.png)

Как результат не очень заметно отсутствие пробела!

**Comment by d13mon** [comment]
я думаю в Clion есть настройки форматирования.
