### ISSUE TITLE
ℹ️ Разделение спринтов

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#21]
https://github.com/ZakharovAleksey/yandex_cpp/blob/1ee392917375ef3c8b2d76ce7d85ec9e441a5d68/main.cpp#L2

Предлагаю со следующего спринта размещать код каждого спринта в отдельной поддиректории проекта. 
Это даст гибкость, облегчит поддержку кода и проверку, можно будет сдавать несколько спринтов параллельно.

И нет необходимости каждый раз создавать отдельный проект в github для каждого спринта. Мы разрабатываем один проект, просто апдейтим его.

main.cpp у вас тоже будет зависеть от спринта, поэтому все исходники лучше группировать в подпапку.

**Comment by ZakharovAleksey** [comment]
Да, абсолютно согласен)
