### ISSUE TITLE
pragma

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#23]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/testing_framework.h#L5-L6

Предлагаю использовать #pragma once вместо define guards. 
Эта директива поддерживается всеми основными компиляторами, она короче и ее использование меньше подвержено багам

**Comment by ZakharovAleksey** [comment]
Согласен, **CLion** делал так по дефолту, а я не обратил особого внимания :)

Замент во всех файлах проекта на `#pragma once`
