### ISSUE TITLE
Данный тест предлагаю разделить на 2 - фильтрации по предикатам и по статусам

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#27]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/server_test.cpp#L234

Тест по предикатам предлагаю сделать для 2-х разных предикатов (фильтров)

**Comment by ZakharovAleksey** [comment]
Согласен, разбил на два:
1. `TestFindDocumentsWithDefaultDocumentStatusFilterFunction` - проверяет результат работы сервеа с **СТАНДАРТНОЙ** функцией для фильтрации документов
2. `TestFindDocumentsWithCustomDocumentStatusFilterFunction` - проверяет результат работы сервеа с **ЗАДАННОЙ ПОЛЬЗОВАТЕЛЕМ** функцией для фильтрации документов
