### ISSUE TITLE
rel

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#28]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/server_test.cpp#L183-L199

Предлагаю ожидаемую релевантность вместо вещественного литерала записывать через формулу `log(documents_count * 1.0/a)*(b/c)`, где a,b,c подставляются в зависимости от тест-кейса. 

Это повысит гибкость и улучшит читаемость теста.

И предлагаю обойтись без умножения, а работать с вещественными значениями релеванстности.  Это увеличивает код и повышает вероятность ошибки

**Comment by ZakharovAleksey** [comment]
Новое название теста: `TestDocumentRelevanceCalculation`.

Добавил `std::map` у которой:
* **Ключ** - это слово из запроса на релевантность документа (только из запроса, нет слов из документов, так как они не нужны для подсчета релевантности)
* **Значение** - это `std::map` у которой:
    * **Ключ**: номер документа
    * **Значение** - частота с которой данное слово встречается в документе, если ни разу - то 0.

Пример:
```cpp
const std::map<std::string, std::map<int, double>> words_rating_data = {
    {"fluffy",       {{1, 0.},  {2, 0.5},  {3, 0.}}},
    {"well-groomed", {{1, 0.},  {2, 0.},   {3, 0.25}}},
    {"cat",          {{1, 0.2}, {2, 0.25}, {3, 0.}}}
};
```

Потом, эти данные использую внутри лямбды `calculate_relevance` для подсчета релевантности для каждого из документов и тут-же проверяю их на равенство.
