### ISSUE TITLE
sort

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#29]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/server_test.cpp#L161-L181

Давайте добавим больше документов

Затем получим результат из нескольких документов (также нужен ассерт на количество в результате) и проверим, что они отсортированы

Сортировку лучше проверить в цикле, сравнивая соседние. 

Либо использовать std::is_sorted

https://en.cppreference.com/w/cpp/algorithm/is_sorted

Вариант (3) где передается компаратор. В качестве компаратора можно передавать лямбда, принимающую 2 объекта типа Document и сравнивающую их по релевантности

Не забываем как нужно правильно сравнивать вещественные значения.

**Comment by ZakharovAleksey** [comment]
Измеенения находятся внутри функции `TestFoundDocumentsSortingByRelevance`.

Добавил: 
1. Больше документов
2. Проверку на количество выданых документов
3. Использовал `std::is_sorted` для проверки отсортированнности
