### ISSUE TITLE
Данный тест лучше разделить  на 2 - на проверку сортировки и подсчет релевантности

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#30]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/server_test.cpp#L144

1 тест-кейс = 1 тест. Сортировка и подсчет релевантности - это разные тест-кейсы.

**Comment by ZakharovAleksey** [comment]
Согласен, разделил на:

1. `TestFoundDocumentsSortingByRelevance` - проверяет правильность сортировки
2. `TestDocumentRelevanceCalculation` - проверяет вычисление релевантности
3. `TestServerFindNotMoreDocumentsThanExpected` - проверяет ограничение на количество выданых документов
