### ISSUE TITLE
test naming

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#31]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f12454bf4dd206e873788756d251ef23a1f49f68/sprint_2/server_test.cpp#L144

Именование тестов должно быть максимально подробным.
но не имена вроде TestMatching. Имя теста - это его паспорт. Должно быть максимально понятно какой функционал тестируется

**Comment by ZakharovAleksey** [comment]
Добрый день, Дмитрий!
Извиняюсь за долгий перерыв - был неделю недоступен!

Согласен, и постарался максимально полно переименовать тесты.
