### ISSUE TITLE
❗РЕГРЕССИЯ: Код не запустится

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#32]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/server_test.h#L10-L26

Объявления не соответствуют определениям

Перед сдачей на ревью рекомендую компилировать и собирать проект

**Comment by ZakharovAleksey** [comment]
Да, спасибо! 
Я забыл про это - и у меня видимо не работает флаг **treat warning as error**, так как аомпиляция проходила успешно.
