### ISSUE TITLE
❗Это не относится к проекту 

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#33]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/intermediate_tasks.h#L5

В проекте на проверку ожидается только код задачи по поисковому серверу

лучше перенести этот код в другие проекты

**Comment by ZakharovAleksey** [comment]
Согласен - создал отдельную папку `intermidiate_tasks` и перенес все файлы туда. 
В дальнейшем буду все промежуточные задания добавлять туда.
