### ISSUE TITLE
Пустые строки не ставим после {

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#34]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/server_test.cpp#L18-L20

**Comment by ZakharovAleksey** [comment]
Как и в [этом](https://github.com/ZakharovAleksey/yandex_cpp/issues/37#issuecomment-807980360) ответе посмотрю автоформатирование в **CLion**.
