### ISSUE TITLE
Именование const

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#35]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/server_test.cpp#L13-L16

kSomething - это именование для статических констант

У нас же локальная переменная с квалификатором const, именуется как переменная

**Comment by ZakharovAleksey** [comment]
Да, спасибо - совсем запутался на тот момент!
