### ISSUE TITLE
sb

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#36]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/server_test.cpp#L122

Предлагаю для распаковки возвращаемых значений использовать удобную фичу C++17 - структурированные привязки

https://en.cppreference.com/w/cpp/language/structured_binding

Например:
```
std::pair<int, std::string> foo() { return {10, "abc"s} };

auto [number,string] = foo();
```

**Comment by ZakharovAleksey** [comment]
Переделал в двух местах: 

1. В первом создание переменной сделал как вы порекомендовали выше через **structured binding**.
2. Во втором добавил лямбду чтобы избавиться от `std::get<0>(...)`

**Comment by d13mon** [comment]
в силе

` matching_words = std::get<0>(server.MatchDocument("cat dog -puppy", general_document_id));`

Поищите по get<

**Comment by ZakharovAleksey** [comment]
Да, согласен!

И я совсем забыл что можно сделать через `std::tie(some_valiable, _)`. Поправил

**Comment by d13mon** [comment]
Можно через tie
