### ISSUE TITLE
⚠️ space

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#37]
https://github.com/ZakharovAleksey/yandex_cpp/blob/36ea03aa3f9e3bb0e1c87ddebba82b3bd3a29b33/sprint_2/server_test.cpp#L232

auto&[document_id, actual_relevance] - пробел нужен

**Comment by ZakharovAleksey** [comment]
Хорошо - изменю настройки автоформатирования в **CLion**. 
Так как я делаю авто-форматирования для всего файла как заканчиваю разработку.

**Comment by d13mon** [comment]
```
const auto&[document_id, actual_relevance]
 auto[matching_words, _]
```

Все в силе, не по кодстайлу. Давайте поправим если не чрез автонастройку, значит вручную, но форматирование везде должно быть корректное

**Comment by d13mon** [comment]
Поставлю "сдал" , но в следующем спринте жду корректного форматирования и исправления всех issue :)

**Comment by ZakharovAleksey** [comment]
Большое спасибо :)

Я наконец дошел до форматирования - как писал [тут](https://github.com/ZakharovAleksey/yandex_cpp/issues/39#issuecomment-808857514) я слделал `.clang-format` файл. Будут еще замечания по форматированию - поправлю там)
