### ISSUE TITLE
Лучше проверять при разборе слов

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#41]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.h#L57-L59

Каждое слово в одном цикле где  std::for_each  в MakeUniqueNonEmptyStrings. там можно обычный цикл

Чтобы не делать это отдельно - это не эффективно

**Comment by ZakharovAleksey** [comment]
Согласен, вынес метод `IsWordValid` из класса, так как он не совсем имеет прямое к нему отношение, перенес проверу в функцию `MakeUniqueNonEmptyStrings`.
