### ISSUE TITLE
❗ТЗ не выполнено

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#42]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.h#L4

> 5.	Метод GetDocumentId должен выбрасывать исключение out_of_range, если индекс переданного документа выходит за пределы допустимого диапазона (0; количество документов).

такого метода даже нет

**Comment by ZakharovAleksey** [comment]
Да, забыл добавить :) Добавил метод `GetDocumentId `.
