### ISSUE TITLE
CheckDocumentInput

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#43]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.cpp#L40

Возвращайте пару - флаг и сообщение об ошибке

Метод с таким именем должен возвращать bool

**Comment by ZakharovAleksey** [comment]
Переделал, теперь функция имеет сигнатуру:
```cpp
std::pair<bool, std::string> CheckDocumentInput(int document_id, const std::string &document);
```

Пример вызова: 
```cpp
if (auto [is_correct, error_message] = CheckDocumentInput(document_id, document); !is_correct)
        throw std::invalid_argument(error_message);
```
