### ISSUE TITLE
&

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#44]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.cpp#L40

`const auto &error_message = `

Присваивать по ссылке возвращаемое значение опасно. Используйте копию или move

**Comment by ZakharovAleksey** [comment]
Теперь такой ошибки нет. Подробнее отписался в комменте: [тут](https://github.com/ZakharovAleksey/yandex_cpp/issues/43#issuecomment-813055970)
