### ISSUE TITLE
assert

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#45]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.cpp#L167-L170

- Мы теперь умеем ставить ассерты. Поставим ассерты на наличие слова в map (word_to_document_frequencies_), a также на деление на 0

- Используем map::count() для проверки наличия элемента в контейнере

- Вызывать count() и at() нужно минимальное количество раз. Используем переменные в случае необходимости

- В основном коде SearchServer (не юнит тестах и модуле тестирования) лучше использовать везде assert из `<cassert>` 
В целом наш самописный макрос ASSERT используется в учебных целях во 2-м спринте в юнит-тестах

**Comment by ZakharovAleksey** [comment]
Добавил `assert`.

 **Вопрос:** в каких случаях в коде лучше использовать `assert` чем просто выкидывать `exception`? И как часто это принято делать?)

**Comment by d13mon** [comment]
у ассертов другие цели.  Они работает в debug-версии проекта. Их легче отлаживать чем исключения - сразу видна строка ошибки, а исключения могут броситься очень далеко от места отлова. 

Ставить можно всегда, а вот исключения только для проверки ошибок релиза. Т. е все внутренние ошибки проверяем ассертами
