### ISSUE TITLE
Здесь лучше ассерт поставить

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#47]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.cpp#L119

**Comment by ZakharovAleksey** [comment]
Поставил `assert`.

Плюс есть вопрос по `assert`. Вот [тут](https://github.com/ZakharovAleksey/yandex_cpp/issues/45#issuecomment-813056386)
