### ISSUE TITLE
char

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#48]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8610898250d38ad51558f16e782c1da055fbd3cb/sprint_3/server.cpp#L95

Лучше не преобразовывать к int и не ипользовать коды, т.к это по сути магические числа. 
Используем char и непосредственно символьные литералы
Так код будет нагляднее

**Comment by ZakharovAleksey** [comment]
Исправил - теперь нет преобразование к `int`, только сравнение с крайними спец-символами.
