### ISSUE TITLE
⚠️FORMAT: Не делаем отступы для спецификаторов

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#49]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/paginator.h#L29

В кодстайле гугла 1 пробел отступ ,но нам это не подходит т.к. у нас отступы 4 пробела, а не 2 как у них

Во всех классах

**Comment by ZakharovAleksey** [comment]
Изменил `clang` настройки чтобы это поправить :)
```cpp
IndentWidth: 4
AccessModifierOffset: -2
```

**Comment by d13mon** [comment]
в силе: отступ вообще не нужен для спецификаторов

**Comment by ZakharovAleksey** [comment]
Понял, поменял `clang` на:
```cpp
IndentWidth: 4
AccessModifierOffset: 0
```

**Comment by d13mon** [comment]
Если невозможно нормально сделать через настройки - сделаем вручную

**Comment by ZakharovAleksey** [comment]
Поправил через `clang`. Изначально не понял какой должен быть отсутп :octocat: 
Сделал вот такие настройки.
```python
IndentWidth: 4
AccessModifierOffset: -4
```

В итоге отстутпы теперь везде вот такие:

![image](https://user-images.githubusercontent.com/18697972/115297758-40735080-a165-11eb-9aa2-02c9ada40c2b.png)

**Comment by d13mon** [comment]
Отлично!
