### ISSUE TITLE
с

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#50]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/paginator.h#L65

Во всем коде:

Codestyle: Имена переменных должны быть длинными и понятными. Каждый раз, когда вы пишете одно-двух-буквенное название переменной или используете что-то вроде cur, должно возникать неприятное чувство

Если сокращение используется в теории или книгах, то по причине сокращения кода. В реальных программах рекомендуется писать подробные и значащие имена. 

Предлагаю в нашем коде тоже это сделать т.е.просмотреть весь код, убрать все сокращения и абстракции. Сделать имена понятными, чтобы код стал самодокументируемым.

Практически никогда лучше не писать сокращенно и/или малоинформативно idx, cur, curr, iter, cmp, comp, diff, tmp, temp, ptr, res, len, sz, gen, pred и т.д.

Именовать str, p, ptr, sz или добавлять _str, _ptr, sz_ - это по сути  следовать венгерской нотации (https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BD%D0%B3%D0%B5%D1%80%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D1%8F)
А это не рекомендуется по кодстайлу.

Однобуквенные имена только для индексов в простом цикле for (не range-based)

Исключения: ex = exception в catch; Имена индексов i,j,k и т.д  в простом цикле for; короткие именования итераторов - it, beg, end, mid (сродни индексам)

Аббревиатуры и стандартные сокращения возможны если есть общепринятые устоявшиеся понятия, прописанные например в Википедии. 

Цифры в именах как правило тоже нужно исключать если нет объективных оправданий. Например, вместо it1, it2 лучше писать it_first, it_second

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

**Comment by ZakharovAleksey** [comment]
Сорри, пропустил - исправил на `container` и поискал подобные места в коде и поправил.
