### ISSUE TITLE
ctr init

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#51]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/paginator.h#L31-L44

В конструкторе лучше не размещать никакой функциональный код. Только простую инициализацию полей данных

Весь функциональный код выносится в другие методы. При необходимости можно создать Init-метод, который будет вызваться после конструктора

Проблема в том, что:
1) конструкторы сложно протестировать в Unit-тестах
2) В конструкторах есть сложности с исключениями
3) Конструкторы не могут ничего возвратить, например код ошибки

Как реализуется:

1. Конструктор с аргументами убирается т.к он уже не сможет инициализировать (инвариант класса будет нарушен)
2. Добавляется дефолтный конструктор без аргументов, как правило =default
3. Добавляется открытый метод Init(<список арументов как у конструктора>);
4. Во внешнем коде вызывается дефолтный CTR, а затем метод Init(...)
5. Можно еще добавить метод, проверяющий инициализацию  - например empty(), is_null(), is_initialized() 

Для создания Paginator предлагаю использовать конструкцию ```Paginator<decltype(std::begin(container))> paginator;```
Так мы определяем тип итератора

По decltype:
https://en.cppreference.com/w/cpp/language/decltype

**Comment by ZakharovAleksey** [comment]
Сделал как описано:
1. Добавил метод `Init(...)`
2. Удалил конструктор с аргументами
3. Добавил дефолтный конструктор
