### ISSUE TITLE
pages

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#53]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/paginator.h#L31-L44

Усложнено, зарефакторим

- Будем использовать цикл while
- Будем поддерживать число оставшихся элементов - int left  и итерировать пока это число  > 0
- Будем отнимать от left размер страницы на каждой итерации
- Будем использовать переданный begin как текущий итератор и двигать его
- Не забываем что на последней итерации число элементов может быть меньше page_size

**Comment by ZakharovAleksey** [comment]
Сделал рефакторинг по алгоритму.
