### ISSUE TITLE
query_result

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#55]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/request_queue.h#L42

- Будем хранить raw_query и число документов в запросе
- Все результаты хранить излишне

**Comment by ZakharovAleksey** [comment]
Поменял члены класса:
Теперь хранится строка и число результатов. Так же добавил метод `IsEmpty()` :)
