### ISSUE TITLE
Не будем писать лишний код

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#56]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/request_queue.h#L45-L47

Структура простая, достаточно одних полей

**Comment by ZakharovAleksey** [comment]
Убрал конструктор по умаолчанию, но оставил конструктор с аргументами для корректной работы: 
```cpp
std::vector<QueryResult> vec.
vec.emplate_back(query, documents_count);
```

**Comment by d13mon** [comment]
ок
