### ISSUE TITLE
GETTER

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#57]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5d656bd27aefc1498eadaa51b10dbb71e7015849/sprint_4/request_queue.cpp#L18-L21

Применять каждый раз алгоритм - это гонять цикл. Это не эффективно

Сделаем простой геттер. Для этого будем поддерживать текущее количество пустых запросов как член класса

**Comment by ZakharovAleksey** [comment]
Сделал рефакторинг программы так чтобы избавить от этого цикла:

1. Создал `private` член класса, который хранит число пустых документов: `empty_responses_count_` 
2. При добавлении элемента - я проверяю, вернул ли сервер пустой отклик на `FindTopDocuments` запрос. И если пустой, то делаю `++empty_responses_count_`
3. Если при добавлении запроса `std::deque<>` переполнен и первый элемент пустой - делаю `--empty_responses_count_`

**Comment by d13mon** [comment]
все верно
