### ISSUE TITLE
size_t

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#58]
https://github.com/ZakharovAleksey/yandex_cpp/blob/1cda96eb835c64f7615c80f03f36a3e858b5dd88/sprint_4/request_queue.h#L51

- Codestyle: Рекомендации по использованию целых типов
https://google.github.io/styleguide/cppguide.html#Integer_Types

- Unsigned целые (кроме size_t в качестве индексов и размеров) в целом не рекомендуются к использованию из-за потенциальных проблем с ними.
Общая рекомендация по коду.

 - size_t может использоваться в коде только в качестве индексов и размеров исходя из семантики типа.
https://en.cppreference.com/w/cpp/types/size_t

___

Лучше int здесь

**Comment by ZakharovAleksey** [comment]
Понял, поменял `size_t` на `int` тут и в других местах.
