### ISSUE TITLE
rfct

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#60]
https://github.com/ZakharovAleksey/yandex_cpp/blob/1cda96eb835c64f7615c80f03f36a3e858b5dd88/sprint_4/request_queue.h#L22-L36

Выделим private метод для апдейта информации о запросах

**Comment by ZakharovAleksey** [comment]
Создал отдельный метод, отвецающий за изменение `requests_`: `UpdateRequestsInformation(responce)`
