### ISSUE TITLE
❗Злоупотребление с size_t

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#61]
https://github.com/ZakharovAleksey/yandex_cpp/blob/1cda96eb835c64f7615c80f03f36a3e858b5dd88/sprint_4/paginator.h#L35-L36

- Codestyle: Рекомендации по использованию целых типов
https://google.github.io/styleguide/cppguide.html#Integer_Types

- Unsigned целые (кроме size_t в качестве индексов и размеров) в целом не рекомендуются к использованию из-за потенциальных проблем с ними.
Общая рекомендация по коду.

 - size_t может использоваться в коде только в качестве индексов и размеров исходя из семантики типа.
https://en.cppreference.com/w/cpp/types/size_t

_______

Не индекс, не размер  -не используем

**Comment by ZakharovAleksey** [comment]
Поменял, спасибо.
