### ISSUE TITLE
class

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#63]
https://github.com/ZakharovAleksey/yandex_cpp/blob/8be4f6510dfa6eff277a10038784cad89f30a97a/sprint_4/request_queue.h#L50

Методы в отдельной секции

__________

https://google.github.io/styleguide/cppguide.html#Declaration_Order

- Группировка public/protected/private имеет приоритет
Сначала рекомендуется размещать публичный интерфейс класса, а потом protected и private методы.

- Внутри одного блока public/protected/private:

Сначала идут типы (в том числе using/typedef)

Следом константы, тоже в отдельной секции.

Затем методы.

Члены лучше размещать в самом низу в отдельной секции (protected/private).

Специальные методы (Конструкторы, деструкторы, operator=) идут после констант.

- Каждая группа (методы, члены, константы и т.д.) отделяется своим спецификатором доступа public/protected/private для лучшей читаемости

- Все определения (не объявления) методов разделены пустой строкой. Перед (но не до) квалификаторами доступа лучше поставить пустую строку.

- Методы, не изменяющие класс (геттеры, чеккеры и др) помечены квалификатором const

- Члены данных в классе (не в struct) именуются с подчеркиванием в конце (`int abc_;`)

Пример:

```
class Foo { 
public:
    struct S{};
   
public;
    static const int kConst = 100;
    
public:
    Foo() = default;
    
public: 
    int get() const {return 0;}

protected: 
    void bar();
   
private:
    struct X {};
    
private:
    static const int kPrivateConst = 111;
    
private:
    void foo() {}
    
private:
    int data_ = 0;
    double precision_ = 0;
    std::string error_;
};
```

**Comment by ZakharovAleksey** [comment]
Поправил - создал отдельную `private` секцию для метода :)
