### ISSUE TITLE
erase

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#64]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5995ded77d2b2b64b6f4fb185faebb238b1b3e18/src/sprint_5/search_server.cpp#L190-L203

- Нам нужно удалять по id документа из всех структур-членов данных, в том числе и из тех где хранятся слова и частота их попадания

- Предпочтительнее методы контейнеров с аналогичным функционалом нежели алгоритмы. Как правило они реализованы эффективнее. Например у std::map есть метод erase(element)

В целом с данной сигнатурой есть метод почти у каждого стандартного контейнера:
```size_type erase( const key_type& key );```

- Прежде  чем удалить из `std::map<int, std::map<std::string, double>>`  нам нужно:

 - в  `std::map<std::string, std::map<int, double>>` по каждому слову из документа получить внутреннюю map и в ней поудалять значения, относящиеся к искомому document_id. 
 Для получения всех слов в документе используем map.at(document_id)

--

- Также в word_to_document_frequencies_ нам нужно не внутренние map поудалять из внешней map, а по каждому слову найти внутреннюю map и в ней поудалять значения, относящиеся к искомому document_id

----

В данном случае у нас 3 однострочных вызова erase()
И только для word_to_document_frequencies_; нужно использовать цикл, чтобы пройтись по словам и удалить для них связанные doc_id = id_to_remove

- Уберем RemoveByDocumentId

**Comment by ZakharovAleksey** [comment]
Хорошо, не думал что `erase()` корректно работает по значению, если оно не найдено.
Поэтому и писал `RemoveDocumentById()` которая как раз использовала `erase`, но по итератору :)

```cpp
template <class Container>
void RemoveByDocumentId(Container &container, DocumentId index) {
    if (auto position = container.find(index); position != container.end())
        container.erase(position);
}
```

Поправил)
