### ISSUE TITLE
GetWordFrequencies

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#65]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5995ded77d2b2b64b6f4fb185faebb238b1b3e18/src/sprint_5/search_server.cpp#L178-L188

Усложнено, зарефакторим

- `static std::map<Word, double> result; `- переименуем в что-то со значением "заглушка", "дефолтный вариант"
-  `result.clear();` - излишне
- уберем find и insert
- используем методы count и at для std::map

**Comment by ZakharovAleksey** [comment]
Сделал рефактор - теперь: 

```cpp
const std::map<Word, double> &SearchServer::GetWordFrequencies(DocumentId index) const {
    static std::map<Word, double> default_option;

    if (words_frequency_by_documents_.count(index) > 0)
        return words_frequency_by_documents_.at(index);

    return default_option;
}
```
