### ISSUE TITLE
remove dupl

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#66]
https://github.com/ZakharovAleksey/yandex_cpp/blob/5995ded77d2b2b64b6f4fb185faebb238b1b3e18/src/sprint_5/search_server.cpp#L205-L231

Усложнено

 Предлагаю сделать так:

> - Т.к document_ids_ - это у нас std::set, значит он хранит document id отсортированными по возрастанию. Следовательно в цикле` for(auto document_id : search_server)` будем осуществлять обход документов по возрастанию id ( это основной цикл for)
> - Локально поддерживаем структуру `map<set<string>, int> existing_word_sets`, которая по уникальному набору слов хранит наименьший id документа
> - В основном цикле  for  получаем set <слов > и проверяем, есть ли такой в existing_word_sets. Если есть, то значит встретили дубликат т.к из-за специфики обхода мы будем всегда встречать первым и добавлять в existing_word_sets наименьший id для любого набора слов.
> - Для преобразования узлов std::map (при обходе) в список слов можно использовать std::transform. > Так мы получаем std::set < std::string > - набор уникальных слов в документе ,который используем в дальнейшем при проверке >frequency нам не > - Если frequency при распаковке нам не нужно, то можем использовать имя "_".

**Comment by ZakharovAleksey** [comment]
Согласен, немного замудрил с определением индекса для удаления. Переделал :)
