### ISSUE TITLE
⚠️if

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#68]
https://github.com/ZakharovAleksey/yandex_cpp/blob/b4ab1742bd1d3ec7e56cb1af3b0ce4d030891299/src/sprint_5/search_server.cpp#L208-L212

Кодстайл: если есть else то уже везде нужны {}

**Comment by d13mon** [comment]
в силе. Исправим

**Даже в сданных спринтах все незакрытые тикеты должны быть исправлены, иначе в следующий раз "можно лучше"/"сдал" не будет поставлено до закрытия всех тикетов в рамках текущего спринта.**

**Comment by ZakharovAleksey** [comment]
Поправил! Теперь `if` и `else` внутри `{}`.
