### ISSUE TITLE
⚠️Лучше auto

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#69]
https://github.com/ZakharovAleksey/yandex_cpp/blob/b4ab1742bd1d3ec7e56cb1af3b0ce4d030891299/src/sprint_5/search_server.cpp#L200

**Comment by d13mon** [comment]
в силе

**Comment by ZakharovAleksey** [comment]
Поправил!

Но, вопрос - почему лучше `auto`? 

Вроде тип простой, не громоздкий для написания. А, на сколько я в курсе, `auto` может увеличивать время компиляции программы если их очень много в коде, поэтому в ситуации с простыми типами лучше явно прописать тип? Или я не прав? :)

**Comment by d13mon** [comment]
Все очень просто: auto 4 символа, а было10. Зачем писать лишний код.

Про увеличение времени компиляции не слышал, такого ограничения насколько я знаю нет - можно пользоваться auto свободно для сокращения кода. Если выведение типа и влияет на компиляцию, то незначительно.  Простой тип это int, bool, Foo, Type, а DocumentId достаточно громоздкий
