### ISSUE TITLE
⚠️auto

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#70]
https://github.com/ZakharovAleksey/yandex_cpp/blob/b4ab1742bd1d3ec7e56cb1af3b0ce4d030891299/src/sprint_5/search_server.cpp#L214

**Comment by d13mon** [comment]
в силе

**Comment by ZakharovAleksey** [comment]
Поправил и оставил вопрос в комментарии: [тут](https://github.com/ZakharovAleksey/yandex_cpp/issues/69#issuecomment-841634092)
