### ISSUE TITLE
asserts

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#72]
https://github.com/ZakharovAleksey/yandex_cpp/blob/140a26de7c2d879aa4b4e7234bcbfd07e9a55648/src/sprint_6/single_linked_list.h#L148

Поставим ассерты во всех наших реализованных методах. Будем проверять указатели на nullptr и список на непустоту там где нужно. 
Это хорошая практика + будет полезно при отладке. 

Предлагаю ставить по принципу: 1 проверка = 1 ассерт т.е разобьем конструкции вроде:

`assert(a || b || c);`

на

```
assert(a);
assert(b);
assert(c);
```
Иначе когда ассерт сработает, то он нам ничего не даст т.к сложно будет понять, какое условие провалилось.

**Comment by ZakharovAleksey** [comment]
Добавил `assert` в методы `PopFront()`, `EraseAfter()`, `InsertAfter`.
