### ISSUE TITLE
check

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#73]
https://github.com/ZakharovAleksey/yandex_cpp/blob/140a26de7c2d879aa4b4e7234bcbfd07e9a55648/src/sprint_6/single_linked_list.h#L158

Вместо проверок на некорректное состояние или некорректное использование внешним кодом будем ставить ассерты

**Comment by ZakharovAleksey** [comment]
Исправил введенеием `assert`. Подробнее в [этом](https://github.com/ZakharovAleksey/yandex_cpp/issues/72#issuecomment-841634345) комментарии :)
