### ISSUE TITLE
assign

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#74]
https://github.com/ZakharovAleksey/yandex_cpp/blob/140a26de7c2d879aa4b4e7234bcbfd07e9a55648/src/sprint_6/single_linked_list.h#L95-L113

 - Напишем приватный метод Assign

Сигнатура:

```
template <typename InputIterator>
void Assign(InputIterator from, InputIterator to)
```

- Следующие 2 конструктора будут просто вызывать его:

```
SingleLinkedList(std::initializer_list<Type> values);
SingleLinkedList(const SingleLinkedList& other);
```

- В Assign будем в цикле от from до to заполнять временный список, а в конце сделаем swap

Это гарантирует, что при любом выброшенном исключении инвариант нашего целевого списка не будет нарушен

**Comment by ZakharovAleksey** [comment]
Реализовал метод `Assign` и поменял имплементацию конструкторов: 

```cpp
SingleLinkedList(std::initializer_list<Type> values) {
    Assign(values.begin(), values.end());
}

SingleLinkedList(const SingleLinkedList& other) {
    Assign(other.begin(), other.end());
}
```
