### ISSUE TITLE
усложнено, упростим и в 1 строку сделаем

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#75]
https://github.com/ZakharovAleksey/yandex_cpp/blob/140a26de7c2d879aa4b4e7234bcbfd07e9a55648/src/sprint_6/single_linked_list.h#L216-L217

**Comment by d13mon** [comment]
в силе

снимаем константность у типа Node* , применяем к head_

SingleLinkedList<Type> здесь незачем

**Comment by ZakharovAleksey** [comment]
Да, понял - переделал на:
```cpp
return ConstantIterator (&const_cast<Node&>(head_));
```
