### ISSUE TITLE
вызовем просто cbefore_begin

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#76]
https://github.com/ZakharovAleksey/yandex_cpp/blob/140a26de7c2d879aa4b4e7234bcbfd07e9a55648/src/sprint_6/single_linked_list.h#L221-L222

**Comment by d13mon** [comment]
ConstantIterator() - это лишнее, там уже возвращается итератор

**Comment by ZakharovAleksey** [comment]
Поменял `return ConstantIterator(cbefore_begin());` на `return cbefore_begin();`
