### ISSUE TITLE
заведем псевдоним для  ArrayPtr<Type> 

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#78]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f01eac53fb9ce44b61c2dbd695ff3ef6a827502e/src/sprint_7/simple_vector.h#L29

**Comment by ZakharovAleksey** [comment]
Сделал!

Добавил `using TypeSmartPtr = ArrayPtr<Type>;` и поменял все вхождения.
