### ISSUE TITLE
⚠️pb

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#80]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f01eac53fb9ce44b61c2dbd695ff3ef6a827502e/src/sprint_7/simple_vector.h#L84-L115

- Алгоритм: 
-- Определим новый размер списка: new_size = size_ + 1
-- Если (new_size > capacity_) то вычислим новое capacity через max из new_size и двойной вместимости, 
создадим временный ArrayPtr через ReallocateCopy, добавим в него новый элемент по индексу size_, сделаем в конце swap
-- Иначе просто добавим элемент по индексу size_ ( в конец)
-- Присвоим новый размер

**Comment by ZakharovAleksey** [comment]
Переделал по алгоритму (аналогично с `PushBack(const Type&& ` )!

```cpp
void PushBack(const Type& value) {
        size_t new_size = size_ + 1u;
        if (new_size > capacity_) {
            size_t new_capacity = (capacity_ != 0) ? std::max(new_size, 2u * capacity_) : 1;
            ReallocateAndCopyData(new_capacity);
        }
        data_[size_] = value;
        size_ = new_size;
    }
```

**Comment by d13mon** [comment]
ReallocateCopy используется в обеих версиях

версии практически идентичны кроме перемещения нового элемента для Move-версии

**Comment by ZakharovAleksey** [comment]
Реализовал `ReallocateAndMoveData` через `std::move()` и использовал этот метод в реализации `PushBack(Type &&)`.
