### ISSUE TITLE
realloc

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#81]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f01eac53fb9ce44b61c2dbd695ff3ef6a827502e/src/sprint_7/simple_vector.h#L25

Реализуем приватный метод для реаллокации списка, который будем вызывать в Reserve, Resize, PushBack

- Создадим ArrayPtr
- Будем перемещать следующее число элементов: `size_t move_size = std::min(new_capacity, size_);`
- Используем move

```
//Сигнатура:
// Выделяет копию текущего массива с заданной вместимостью
template <typename Type>
ArrayPtr<Type> ReallocateCopy(size_t new_capacity);
    
//Вызов:
auto new_items = ReallocateCopy(new_capacity);
```

**Comment by ZakharovAleksey** [comment]
Сделал, но немного по другому! Спасибо за хороший совет :)

Теперь в методах `Reserve`, `Resize` и `PushBack` используется метод `ReallocateAndCopyData`.

```cpp
void ReallocateAndCopyData(size_t new_capacity) {
        TypeSmartPtr new_data(new_capacity);
        std::copy(data_.Get(), data_.Get() + size_, new_data.Get());
        data_.swap(new_data);

        capacity_ = new_capacity;
    }
```

**Comment by d13mon** [comment]
1. Мы используем std::move здесь

2. Если size_ будет больше нового capacity то будет баг, поэтому нужно брать минимум

**Comment by ZakharovAleksey** [comment]
Переделал. Да - про `std::min()` это хороший поинт :)
