### ISSUE TITLE
⚠️insert

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#82]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f01eac53fb9ce44b61c2dbd695ff3ef6a827502e/src/sprint_7/simple_vector.h#L122-L166

- АЛГОРИТМ:
-- Добавим вначале проверки (ассерты) на корректность позиции вставки
-- Определим новый размер списка: new_size = size_ + 1
-- Получим mutable-итератор через найденное смещение const-итератора от начала: 'Iterator mutable_pos = begin() + offset;'
-- Если (new_size <= capacity_) то используем copy(move)_backward. Нам нужно сместитить на 1 вперед все элементы, которые идут после места вставки, а потом вставить в освободившуюся позицию наш элемент.
Позиция вставки у нас есть  - Iterator mutable_pos. От (позиция_вставки + 1) и до end()-1 нужно сместить элементы вправо на 1. Для смещения используется вышеупомянутый алгоритм.
-- Иначе вычислим new_capacity, создадим временный ItemsPtr, проведем  копирование (перемещение) элементов в него до позиции вставки, делаем вставку, 
проведем копирование (перемещение) элеметов в него после позиции вставки, в конце делаем swap
-- Присвоим новый размер, вернем итератор на вставленный элемент

**Comment by ZakharovAleksey** [comment]
Переделал по алгоритму!
Cюда копировать не будет - так как немного громоздко ;)

**Comment by d13mon** [comment]
`const_cast<Iterator>(position)` -  вместо const_cast создаем Iterator из смещения от начала списка

**Comment by ZakharovAleksey** [comment]
Переделал :)

**Comment by d13mon** [comment]
`return element_position;`
Лучше создавать новый итератор при возврате т.к есть риск невалидности итератора
