### ISSUE TITLE
⚠️erase

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#83]
https://github.com/ZakharovAleksey/yandex_cpp/blob/f01eac53fb9ce44b61c2dbd695ff3ef6a827502e/src/sprint_7/simple_vector.h#L168-L176

1) Получим mutable-итератор через найденное смещение const-итератора от начала: 'Iterator mutable_pos = begin() + offset;'

2) Применим std::move для перемещения "хвоста"  - [ mutable_pos +1 , end) на одну позицию влево т.е на позицию mutable_pos

3) Уменьшим size_

4) вернем mutable_pos

**Comment by ZakharovAleksey** [comment]
Переделал по алгоритму!)

```cpp
Iterator Erase(ConstIterator position) {
        for (auto current_position = (Iterator)position; current_position != end() - 1; ++current_position)
            *current_position = std::move(*(current_position + 1));
        --size_;

        return Iterator(position);
    }
```

**Comment by d13mon** [comment]
используем алгоритм std::move вместо for

**Comment by ZakharovAleksey** [comment]
Переделал!
