### ISSUE TITLE
это излишне

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#86]
https://github.com/ZakharovAleksey/yandex_cpp/blob/afbc3a07db0ab8ba3302306ce91c3fcacd382feb/src/sprint_7/array_ptr.h#L16-L17

**Comment by ZakharovAleksey** [comment]
Убрал `if` - он действительно не нужен :) 

Но `std::generate()` необходим, так как до него, во многих местах по коду при создании временных массивов были строчки `std::fill()` или `std::generate()` которые заполняли дефолтными значениями массив. 
Перенеся логику в одно место - в конструктор, я избавился от дублирования описанной выше логики)

**Comment by d13mon** [comment]
хмммм.... ну ок:)
