### ISSUE TITLE
⚠️ЧИТАБЕЛЬНОСТЬ КОДА:  имена методов в разных стилях

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#88]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/concurent_map.h#L96-L125

https://google.github.io/styleguide/cppguide.html#General_Naming_Rules

**Comment by ZakharovAleksey** [comment]
Да, извиняюсь - что-то меня переклинило :) 

Поправил!
