### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#90]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/concurent_map.h#L68

[=] допустимо для небольших лямбда, где ясно, какие переменные захватываются.
Также это решает проблему, когда нам нужно захватить много переменных.

Касательно [&]: Prefer explicit captures if the lambda may escape the current scope
Поэтому лучше захватывать только нужные переменные по ссылке. 

Codestyle:
https://google.github.io/styleguide/cppguide.html#Lambda_expressions

**Comment by ZakharovAleksey** [comment]
В целом согласен с коментарием!

Но тут необходимо захватывать все переменные что есть в лямбде :) Мне кажется конкретно в этом случае лучше будет `[&]`, так как в противном случае будет:

```cpp
futures_vector.emplace_back(
    std::async([&policy, &boundary, &function] { 
        std::for_each(policy, boundary.first, boundary.second, function); }));
```

Но все равно поменял :)

**Comment by d13mon** [comment]
Допустимо, если нет лишних захватов по ссылке

а у нас были: futures_vector, buckets_boundaries, buckets_count, bucket_size, container и т.д. 

когда вы явно показываете, что и как захватываете - это лучше.
