### ISSUE TITLE
Странная логика

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#91]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/search_server.h#L42-L44

Должно с любой политикой работать. Нужен дефолтный вариант если не реализовано

**Comment by ZakharovAleksey** [comment]
Согласен - изначально по описанию задания подумал что необходимы только эти две! Поменял!
