### ISSUE TITLE
⚠️ДУБЛИРОВАНИЕ КОДА

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#95]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/search_server.h#L85-L100

**Comment by ZakharovAleksey** [comment]
Убрал дублирование, использовав тот же метод, но с заданной `ExecutionPolicy`.
