### ISSUE TITLE
match

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#96]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/search_server.h#L116-L117

Чтобы ускорить и сократить код:

- Применим такой предикат для минусовых и плюсовых слов:

```
const auto word_checker = 
        [this, document_id](string_view word) {
            const auto it = word_to_document_freqs_.find(word);
            return it != word_to_document_freqs_.end() && it->second.count(document_id);
        };
 ```       
   
- Для минусовых используем алгоритм any_of с данным предикатом

- Для плюсовых скопируем с помощью алгоритмов в итоговый список, используя данный предикат

- Результат по плюсовым можно отсортировать через sort и отсеять дубли через std::unique

- В алгоритмах STL не забываем использовать execution::par (многопоточные версии)

**Comment by ZakharovAleksey** [comment]
Поправил! Действительно поменьше кода стало))
