### ISSUE TITLE
⚠️parse

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#97]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/search_server.h#L316

У нас не было задачи распараллеливать ParseQuery

Это излишне

**Comment by ZakharovAleksey** [comment]
Я убрал паралельный вызов из всех методов, но саму реализацию оставил и пометил квалификатором `[[maybe_unused]]`. 

**Вопрос**: Разве плохо иметь паралельный аналог этой функции и использовать в тех местах, где передается `ExecutionPolicy`? По коду, вроде, вызывается метод в тех местах, где как раз можно и распарелелить бы было :)

**Comment by d13mon** [comment]
Вы можете написать для себя, но проверяться будет только то, что есть в задании.
