### ISSUE TITLE
string_view

### ISSUE THREAD

**Issue by d13mon** [ZakharovAleksey/yandex_cpp#98]
https://github.com/ZakharovAleksey/yandex_cpp/blob/ac4f57c1b6311ed4acd676ee779649148edb6a05/src/sprint_8/search_server.h#L362

Здесь будем хранить  тоже string_view

**Comment by ZakharovAleksey** [comment]
У меня в этом контейнере хранятся `std::string` на которые я ссылаюсь через `std::string_view` в других контейнерах. В случае замены, как я вижу, нужно будет:
1. Создать дополнительный контейнер `words_storage`, в котором хранятся слова
2. Переписать это поле класса через `std::string_view`
3. Добалять дополнительную логику которая следит за состоянием `words_storage`

Мне кажется это приводит к усложеннию кода, или я что-то не вижу?) 

P.S. Пока не поменял этот момент в коде

**Comment by d13mon** [comment]
А почему вы там храните не ссылки? У нас где-то хранится текст, мы передаем в наш класс этот текст как string_view, парсим его на слова в виде string_view и храним также как string_view
